import Head from "next/head";
import Navbar from "@/components/layouts/navbar";

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function ABLayout({ children, title = "小新的網站" }) {
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="樣版頁" />
      </Head>
      <Navbar />
      <div className="container">{children}</div>
    </>
  );
}
